description = 'Fortify SSC Parser Utilities for parsing CycloneDX files'

apply plugin: 'io.freefair.lombok'

dependencies {
    api project(':fortify-ssc-parser-util-json')
    compileOnly 'com.fortify.plugin:plugin-api'
    testImplementation('org.junit.jupiter:junit-jupiter-params:5.14.4')
    testImplementation('com.fortify.plugin:plugin-api')
}
